// src/lib/confidential/crypto/index.ts
// Export cryptographic primitives for Token-2022 Confidential Transfers
//
// NOTE: ZK proof generation has been moved to the CLI Bridge (cli-bridge.ts)
// The spl-token CLI generates production-grade Bulletproof ZK proofs using Rust.
// The TypeScript placeholder proofs have been deprecated and removed.

export {
  // Types
  type TwistedElGamalKeypair,
  type TwistedElGamalCiphertext,
  
  // Keypair functions
  generateTwistedElGamalKeypair,
  keypairFromSeed,
  
  // Encryption/Decryption
  encrypt,
  encryptWithRandomness,
  decrypt,
  encryptU64,
  decryptU64,
  
  // Homomorphic operations
  addCiphertexts,
  subtractCiphertexts,
  
  // Serialization
  serializeCiphertext,
  deserializeCiphertext,
  serializeKeypair,
  deserializeKeypair,
  
  // Utils
  getHGenerator,
} from './twisted-elgamal';

// ZK Proofs are now generated by the CLI Bridge (spl-token CLI)
// See: src/lib/confidential/cli-bridge.ts
//
// The following types are exported for reference but proof generation
// happens server-side via the Rust CLI:
export type RangeProof = Uint8Array;
export type EqualityProof = Uint8Array;
export type ValidityProof = Uint8Array;
export type ZeroBalanceProof = Uint8Array;
export type TransferProof = {
  rangeProof: RangeProof;
  equalityProof: EqualityProof;
  validityProof: ValidityProof;
};
